apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: unsivilaudio/multi-server
          env:
            - name: PGHOST
              value: postgres-srv
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: 'postgres'
            - name: PGUSER
              value: 'postgres'
            - name: PGPASSWORD
              value: 'postgrespassword'
            - name: REDIS_HOST
              value: redis-srv
            - name: REDIS_PORT
              value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-svc
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
